### ISSUE TITLE
Issue with EPSF Properties field (properties={"epsg": lambda x: x == 32736}) for Datacubes using openEO

### ISSUE THREAD

**Issue by budprat** [Open-EO/openeo-python-client#322]
I tested the method for EPSG filtering, using properties={"epsg": lambda x: x == 32736}, but this leads to the error below,

AttributeError Traceback (most recent call last)
in
----> 1 dc = con.load_collection("S2_L2A_MSI_COG", properties={"epsg": lambda x: x==32736}, spatial_extent={"west": 35.697845493643975, "south": -3.00023922050861, "east": 35.723844360443024, "north": -2.96097480413157}, temporal_extent=["2020-03-05", "2020-03-10"], bands=["B02", "B03", "B04", "B08"])
2 B2 = dc.band("B02")
3 B4 = dc.band("B04")
4 B8 = dc.band("B08")
5 dc = (2.5 * (B8 - B4)) / ((B8 + 6.0 * B4 - 7.5 * B2) + 1.0)

/opt/conda/envs/python/lib/python3.8/site-packages/openeo/rest/connection.py in load_collection(self, collection_id, spatial_extent, temporal_extent, bands, properties)
786 """
787 if self._api_version.at_least("1.0.0"):
--> 788 return DataCube.load_collection(
789 collection_id=collection_id, connection=self,
790 spatial_extent=spatial_extent, temporal_extent=temporal_extent, bands=bands, properties=properties

/opt/conda/envs/python/lib/python3.8/site-packages/openeo/rest/datacube.py in load_collection(cls, collection_id, connection, spatial_extent, temporal_extent, bands, fetch_metadata, properties)
193 arguments['bands'] = bands
194 if properties:
--> 195 arguments['properties'] = {
196 prop: cls._get_callback(pred, parent_parameters=["value"])
197 for prop, pred in properties.items()

/opt/conda/envs/python/lib/python3.8/site-packages/openeo/rest/datacube.py in (.0)
194 if properties:
195 arguments['properties'] = {
--> 196 prop: cls._get_callback(pred, parent_parameters=["value"])
197 for prop, pred in properties.items()
198 }

/opt/conda/envs/python/lib/python3.8/site-packages/openeo/rest/datacube.py in _get_callback(process, parent_parameters)
816 arguments = [ProcessBuilder({"from_parameter": p}) for p in parent_parameters]
817
--> 818 pg = process(*arguments).pgnode
819 else:
820 raise ValueError(process)

AttributeError: 'bool' object has no attribute 'pgnode'

**Comment by soxofaan** [comment]
what version of the openeo client library are you using?
e.g. what does `openeo.client_version()` say?

that snippet of code seems to work with client version 0.11.0

**Comment by soxofaan** [comment]
I can reproduce the problem with version 0.8.2.
I would recommend to upgrade your `openeo` package to a later version
